"""added project

Revision ID: 2441a5cf9e6f
Revises: 470c8d4da70f
Create Date: 2024-11-01 20:58:22.437105

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "2441a5cf9e6f"
down_revision: Union[str, None] = "470c8d4da70f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "project",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "ideacategoryassociation",
        sa.Column("idea_id", sa.UUID(), nullable=False),
        sa.Column("category_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["idea_id"],
            ["idea.id"],
        ),
        sa.PrimaryKeyConstraint("idea_id", "category_id"),
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("category_name_key", "category", ["name"])

    op.drop_table("ideacategoryassociation")
    op.drop_table("project")
    # ### end Alembic commands ###
