"""removed vote counts

Revision ID: 9ba33d492233
Revises: cd9a4e2439f5
Create Date: 2024-11-03 10:50:19.431328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9ba33d492233'
down_revision: Union[str, None] = 'cd9a4e2439f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_idea_vote_count', table_name='idea')
    op.drop_column('idea', 'vote_count')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('idea', sa.Column('vote_count', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_index('ix_idea_vote_count', 'idea', ['vote_count'], unique=False)
    # ### end Alembic commands ###
