"""bugs

Revision ID: cd9a4e2439f5
Revises: fa488e97b738
Create Date: 2024-11-02 11:07:30.947228

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'cd9a4e2439f5'
down_revision: Union[str, None] = 'fa488e97b738'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('idea_category_association',
    sa.Column('idea_id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['idea_id'], ['idea.id'], ),
    sa.PrimaryKeyConstraint('idea_id', 'category_id')
    )
    op.drop_table('ideacategoryassociation')
    op.alter_column('idea', 'project_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('idea', 'creator_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('idea', 'creator_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('idea', 'project_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.create_table('ideacategoryassociation',
    sa.Column('idea_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], name='ideacategoryassociation_category_id_fkey'),
    sa.PrimaryKeyConstraint('idea_id', 'category_id', name='ideacategoryassociation_pkey')
    )
    op.drop_table('idea_category_association')
    # ### end Alembic commands ###
