"""link

Revision ID: fa488e97b738
Revises: ccd0d5e5ea46
Create Date: 2024-11-02 11:01:19.399522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'fa488e97b738'
down_revision: Union[str, None] = 'ccd0d5e5ea46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ideacategoryassociation_idea_id_fkey', 'ideacategoryassociation', type_='foreignkey')
    op.create_foreign_key(None, 'ideacategoryassociation', 'category', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ideacategoryassociation', type_='foreignkey')
    op.create_foreign_key('ideacategoryassociation_idea_id_fkey', 'ideacategoryassociation', 'idea', ['idea_id'], ['id'])
    # ### end Alembic commands ###
